package com.example.homelooker;

import android.content.Context;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteOpenHelper;

public class AdministracionSQLiteOpenHelper extends SQLiteOpenHelper {

    public AdministracionSQLiteOpenHelper(Context context, String name, SQLiteDatabase.CursorFactory factory, int version) {
        super(context, name, factory, version);
    }

    @Override
    public void onCreate(SQLiteDatabase db) {
        db.execSQL("CREATE TABLE user(codigo INTEGER PRIMARY KEY AUTOINCREMENT, correo TEXT, nombre TEXT, usuario TEXT, contrasenia TEXT, rol TEXT)");
        db.execSQL("CREATE TABLE ubicacion(codigo INTEGER PRIMARY KEY, ciudad TEXT, pais TEXT)");
        db.execSQL("CREATE TABLE estancia(codigo INTEGER PRIMARY KEY AUTOINCREMENT, nombre TEXT, precio REAL, tipo TEXT, metros INTEGER, dormitorios INTEGER, descripcion TEXT, caracteristicas TEXT, imagen TEXT, user_cod INTEGER, ubicacion_cod INTEGER, FOREIGN KEY (user_cod) REFERENCES user(codigo), FOREIGN KEY (ubicacion_cod) REFERENCES ubicacion(codigo))");

        db.execSQL("INSERT INTO ubicacion VALUES (1, 'Madrid', 'España'), (2, 'Roma', 'Italia'), (3, 'Lisboa', 'Portugal'), (4, 'Paris', 'Francia')");

        //datos iniciales para que aparezca algo de contenido
        db.execSQL("INSERT INTO estancia (nombre, precio, tipo, metros, dormitorios, descripcion, caracteristicas, imagen, ubicacion_cod) VALUES ('Casa amplia en el centro de Madrid', 150000, 'Vivienda', 148, 3, 'Vivienda de grandes dimensiones situada en el centro de Madrid, con un bonito diseño abovedado en su interior que da un toque muy característico a la vivienda.', '148 metros cuadrados \n 3 habitaciones \n Segunda mano/buen estado \n Construido en 1960 \n Calefacción individual: Bomba de frío/calor', 'https://cdn.pixabay.com/photo/2016/11/29/03/53/house-1867187_1280.jpg', 1)");
        db.execSQL("INSERT INTO estancia (nombre, precio, tipo, metros, dormitorios, descripcion, caracteristicas, imagen, ubicacion_cod) VALUES ('Casa unifamiliar de grandes dimensiones', 190000, 'Vivienda', 178, 4, 'Casa unifamiliar a las afueras de Madrid, con varias habitaciones reformadas. Cuenta con 4 amplias habitaciones con grandes ventanas cada una de ellas. Además cuenta con aire acondicionado y calefacción incorporados. Cuenta con una ubicación excelente ya que se encuentra a pocos minutos de la para de metros más cercana, que conecta directamente con el centro de la ciudad. Contacta con nosotros para obtener la información.', '178 metros cuadrados \n 4 habitaciones \n Habitaciones reformadas \n Orientación norte \n Construido en 1982 \n Aire acondicionado y calefacción', 'https://img.freepik.com/foto-gratis/casa-aislada-campo_1303-23772.jpg?w=996&t=st=1684749204~exp=1684749804~hmac=90fe3102ce8ceab844ce60ef1db1ea266cf1194a4987ea91ac664e6043985766', 1)");
        db.execSQL("INSERT INTO estancia (nombre, precio, tipo, metros, dormitorios, descripcion, caracteristicas, imagen, ubicacion_cod) VALUES ('Casa en la zona de casa de campo para ser reformada', 100500, 'Vivienda', 109, 4, 'Vivienda en la zona de casa de campo de Madrid, actualmente se encuentra en malas condiciones por lo que se requiere realizar una gran reforma en la mismo, es por eso que su precio se encuentra reducido considerablemente ya que entendemos que se requiere invertir dinero en la vivienda para convertirla en habitable.', '109 metros cuadrados \n 4 habitaciones \n Se necesita reforma \n Orientación norte \n Construido en 1900', 'https://cdn.pixabay.com/photo/2017/09/17/18/15/lost-places-2759275_1280.jpg', 1)");
        db.execSQL("INSERT INTO estancia (nombre, precio, tipo, metros, dormitorios, descripcion, caracteristicas, imagen, ubicacion_cod) VALUES ('Piso totalmente amueblado situado en el centro de la ciudad', 249000, 'Piso', 79, 2, 'Piso en tercera planta, el cual ofrece unas maravillosas vistas de la Puerta de Alcalá de Madrid. Viene totalmente amueblado y libre de cargas, perfecto para realizar uina mudanza express.', '79 metros cuadrados \n 2 habitaciones amplias \n Cocina de inducción \n Orientación oeste \n Construido en 2003', 'https://img.freepik.com/foto-gratis/arquitectura-moderna-apartamentos_1268-14696.jpg?w=996&t=st=1684749985~exp=1684750585~hmac=667be0211f1653506d09b0020f0a86c38a21c5a7708c777b0d2fcbb31e55279e', 1)");
        db.execSQL("INSERT INTO estancia (nombre, precio, tipo, metros, dormitorios, descripcion, caracteristicas, imagen, ubicacion_cod) VALUES ('Habitación en piso ubicado en la Avenida Gran Vía', 1150, 'Habitación', 15, 1, 'Habitación de lujo totalmente amueblada en piso compartido en una de las calles más conocidas de Madrid.', '15 metros cuadrados de habitación \n Totalmente amueblada \n Orientación oeste \n Construido en 2010', 'https://img.freepik.com/foto-gratis/sala-estar-lujo-loft-representacion-3d-estanteria_105762-2104.jpg?w=996&t=st=1684750396~exp=1684750996~hmac=d99b952ab0b280e1ced8ed4d32d3c499895d2bb9bd8dcb80cb0af328b928eabc', 1)");
        db.execSQL("INSERT INTO estancia (nombre, precio, tipo, metros, dormitorios, descripcion, caracteristicas, imagen, ubicacion_cod) VALUES ('Chalet de grandes dimensiones con piscina', 450000, 'Chalet', 290, 6, 'Gran chalet a las afueras de Madrid, cuenta con 6 amplias habitaciones y dos salones con grandes decoraciones y todo lujo de detalles para que disfrute el posible comprador de este chalet.', '290 metros cuadrados \n Totalmente amueblada \n Orientación norte \n Construido en 2015', 'https://img.freepik.com/foto-gratis/villa-lujo-piscina-espectacular-diseno-contemporaneo-arte-digital-bienes-raices-hogar-casa-propiedad-ge_1258-150749.jpg?w=996&t=st=1684750515~exp=1684751115~hmac=06d56bfc0242679050926d8fa27dac977baabcee66f6c8162ae8cac505f921ba', 1)");

        db.execSQL("INSERT INTO estancia (nombre, precio, tipo, metros, dormitorios, descripcion, caracteristicas, imagen, ubicacion_cod) VALUES ('Pequeña casa en el campo a las afueras de la ciudad', 55900, 'Vivienda', 53, 1, 'Pequeña vivienda a las afueras de la ciudad fabricada en madera de pino. Es pequeña pero muy acogedora, ideal para disfrutar y desconectar en la naturaleza con un acompañante.', '53 metros cuadrados \n 1 habitación \n Fabricada ecologicamente \n Construido en 2001 \n Calefacción individual: Bomba de frío/calor', 'https://images.pexels.com/photos/2360673/pexels-photo-2360673.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 2)");
        db.execSQL("INSERT INTO estancia (nombre, precio, tipo, metros, dormitorios, descripcion, caracteristicas, imagen, ubicacion_cod) VALUES ('Casa unifamiliar ubicada en la ciudad de Roma', 130000, 'Vivienda', 67, 3, 'Vivienda unifamiliar en la ciudad de roma fabricada con ladrillo macizo. Es pequeña pero acogedora, cuenta con muchos detalles en su interior que recuerdan a la ciudad de Roma, para que te sientas la arquitectura de alrededores tanto dentro como fuera de casa.', '67 metros cuadrados \n 3 habitaciones \n Fabricada con ladrillo de muy buena calidad \n Construido en 1997 \n Calefacción individual: Bomba de frío/calor', 'https://images.pexels.com/photos/259588/pexels-photo-259588.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 2)");
        db.execSQL("INSERT INTO estancia (nombre, precio, tipo, metros, dormitorios, descripcion, caracteristicas, imagen, ubicacion_cod) VALUES ('Apartamento en quinta planta', 86009, 'Piso', 60, 2, 'Apartamento en un bloque de pisos del centro de Roma, viene totalmente amueblado y libre de cargas para que el cliente pueda entrar a vivir lo más rápido posible y sin encontrarse ningún inconveniente.', '60 metros cuadrados \n 2 habitaciones \n Fabricada de materiales de primera calidad \n Construido en 1981 \n Calefacción individual: Bomba de frío/calor', 'https://images.unsplash.com/photo-1558981082-c7d43331cd8c?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1015&q=80', 2)");

        db.execSQL("INSERT INTO estancia (nombre, precio, tipo, metros, dormitorios, descripcion, caracteristicas, imagen, ubicacion_cod) VALUES ('Pequeña casa muy floral', 37000, 'Vivienda', 56, 2, 'Pequeña vivienda en la ciudad de Lisboa con un jardín principal lleno de flores. Es pequeña pero muy acogedora, ideal para disfrutar de ella.', '56 metros cuadrados \n 2 habitaciones \n Fabricada ecologicamente \n Construido en 1939', 'https://images.unsplash.com/photo-1672184159377-4b34ec9e1141?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2070&q=80', 3)");
        db.execSQL("INSERT INTO estancia (nombre, precio, tipo, metros, dormitorios, descripcion, caracteristicas, imagen, ubicacion_cod) VALUES ('Casa unifamiliar con jardín', 130400, 'Vivienda', 100, 3, 'Vivienda unifamiliar en la ciudad de Lisboa fabricada con ladrillo macizo. Es pequeña pero acogedora, cuenta con muchos detalles en su interior que recuerdan a la ciudad de Roma, para que te sientas la arquitectura de alrededores tanto dentro como fuera de casa.', '67 metros cuadrados \n 3 habitaciones \n Fabricada con ladrillo de muy buena calidad \n Construido en 1997 \n Calefacción individual: Bomba de frío/calor', 'https://images.pexels.com/photos/259588/pexels-photo-259588.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 3)");
        db.execSQL("INSERT INTO estancia (nombre, precio, tipo, metros, dormitorios, descripcion, caracteristicas, imagen, ubicacion_cod) VALUES ('Apartamento en quinta planta', 110900, 'Piso', 49, 2, 'Apartamento en un bloque de pisos del centro de Roma, viene totalmente amueblado y libre de cargas para que el cliente pueda entrar a vivir lo más rápido posible y sin encontrarse ningún inconveniente.', '60 metros cuadrados \n 2 habitaciones \n Fabricada de materiales de primera calidad \n Construido en 1981 \n Calefacción individual: Bomba de frío/calor', 'https://images.unsplash.com/photo-1558981082-c7d43331cd8c?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1015&q=80', 3)");

        db.execSQL("INSERT INTO estancia (nombre, precio, tipo, metros, dormitorios, descripcion, caracteristicas, imagen, ubicacion_cod) VALUES ('Pequeña casa en el campo a las afueras de la ciudad de París', 55900, 'Vivienda', 53, 1, 'Pequeña vivienda a las afueras de la ciudad fabricada en madera de pino. Es pequeña pero muy acogedora, ideal para disfrutar y desconectar en la naturaleza con un acompañante.', '53 metros cuadrados \n 1 habitación \n Fabricada ecologicamente \n Construido en 2001 \n Calefacción individual: Bomba de frío/calor', 'https://images.pexels.com/photos/2360673/pexels-photo-2360673.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1', 4)");
        db.execSQL("INSERT INTO estancia (nombre, precio, tipo, metros, dormitorios, descripcion, caracteristicas, imagen, ubicacion_cod) VALUES ('Apartamento de varias plantas en el centro de París', 130000, 'Vivienda', 150, 4, 'Vivienda de varias plantas con estilo gótico en plenop centro de París, a escasos metros de los monumentos más emblematicos de la ciudad', '150 metros cuadrados \n 4 habitaciones \n Fabricada con materiales originarios de la ciudad \n Construido en 1919 \n Calefacción individual: Bomba de frío/calor', 'https://images.unsplash.com/photo-1566477479474-c8562ac321dc?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1470&q=80', 4)");
        db.execSQL("INSERT INTO estancia (nombre, precio, tipo, metros, dormitorios, descripcion, caracteristicas, imagen, ubicacion_cod) VALUES ('Apartamento en quinta planta', 380100, 'Chalet', 350, 7, 'Chalet fabricado totalmente de madera situado a las afueras de París, cuenta con gran cantidad de detalles lujosos y un cocina muy espaciosa completamente equipada con la última tecnología', '350 metros cuadrados \n 7 habitaciones \n Fabricada de materiales de primera calidad \n Construido en 2004 \n Calefacción individual: Bomba de frío/calor \n Cocina totalmente equipada', 'https://images.unsplash.com/photo-1571055107559-3e67626fa8be?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1631&q=80', 4)");

        db.execSQL("CREATE TABLE favoritos(codigo INTEGER PRIMARY KEY AUTOINCREMENT, nombre TEXT, ubicacion TEXT, correo TEXT)");
    }

    @Override
    public void onUpgrade(SQLiteDatabase db, int oldVersion, int newVersion) {

    }
}
